version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

  settings:
    funlen:
      lines: 150
      statements: 80

    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/boba180799/anti-bruteforce
            - google.golang.org/grpc
            - google.golang.org/grpc/test/bufconn
            - google.golang.org/protobuf
            - google.golang.org/genproto
            - github.com/grpc-ecosystem/grpc-gateway
            - github.com/spf13/cobra