// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: v1/antibruteforce.proto

package pbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IpRuleType — тип правила IP-адресов.
type IpRuleType int32

const (
	IpRuleType_IP_RULE_TYPE_UNSPECIFIED IpRuleType = 0
	// IP_RULE_TYPE_WHITELIST — доверенные подсети.
	// Авторизация с них разрешается безусловно.
	IpRuleType_IP_RULE_TYPE_WHITELIST IpRuleType = 1
	// IP_RULE_TYPE_BLACKLIST — запрещённые подсети.
	// Авторизация с них отклоняется безусловно.
	IpRuleType_IP_RULE_TYPE_BLACKLIST IpRuleType = 2
)

// Enum value maps for IpRuleType.
var (
	IpRuleType_name = map[int32]string{
		0: "IP_RULE_TYPE_UNSPECIFIED",
		1: "IP_RULE_TYPE_WHITELIST",
		2: "IP_RULE_TYPE_BLACKLIST",
	}
	IpRuleType_value = map[string]int32{
		"IP_RULE_TYPE_UNSPECIFIED": 0,
		"IP_RULE_TYPE_WHITELIST":   1,
		"IP_RULE_TYPE_BLACKLIST":   2,
	}
)

func (x IpRuleType) Enum() *IpRuleType {
	p := new(IpRuleType)
	*p = x
	return p
}

func (x IpRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_antibruteforce_proto_enumTypes[0].Descriptor()
}

func (IpRuleType) Type() protoreflect.EnumType {
	return &file_v1_antibruteforce_proto_enumTypes[0]
}

func (x IpRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpRuleType.Descriptor instead.
func (IpRuleType) EnumDescriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{0}
}

// CheckAttemptRequest — запрос проверки попытки авторизации.
type CheckAttemptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Логин пользователя. Обязательное поле.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Пароль пользователя. Обязательное поле.
	// Используется для защиты от обратного brute-force.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// IP-адрес клиента в текстовом виде (IPv4).
	Ip            string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAttemptRequest) Reset() {
	*x = CheckAttemptRequest{}
	mi := &file_v1_antibruteforce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptRequest) ProtoMessage() {}

func (x *CheckAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptRequest.ProtoReflect.Descriptor instead.
func (*CheckAttemptRequest) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAttemptRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CheckAttemptRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CheckAttemptRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// CheckAttemptResponse — ответ проверки.
type CheckAttemptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true — попытка разрешена, false — заблокирована.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAttemptResponse) Reset() {
	*x = CheckAttemptResponse{}
	mi := &file_v1_antibruteforce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptResponse) ProtoMessage() {}

func (x *CheckAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptResponse.ProtoReflect.Descriptor instead.
func (*CheckAttemptResponse) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAttemptResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ResetBucketRequest — запрос сброса вёдер.
type ResetBucketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Логин, чьё ведро нужно сбросить. Опционально.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// IP-адрес, чьё ведро нужно сбросить. Опционально.
	Ip            string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBucketRequest) Reset() {
	*x = ResetBucketRequest{}
	mi := &file_v1_antibruteforce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketRequest) ProtoMessage() {}

func (x *ResetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketRequest.ProtoReflect.Descriptor instead.
func (*ResetBucketRequest) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{2}
}

func (x *ResetBucketRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ResetBucketRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// IpRule — правило для одной CIDR-подсети.
type IpRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CIDR-подсеть, например "192.168.1.0/24".
	Cidr string `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	// Тип правила.
	Type IpRuleType `protobuf:"varint,2,opt,name=type,proto3,enum=antibruteforce.v1.IpRuleType" json:"type,omitempty"`
	// Произвольное описание для администратора.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpRule) Reset() {
	*x = IpRule{}
	mi := &file_v1_antibruteforce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpRule) ProtoMessage() {}

func (x *IpRule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpRule.ProtoReflect.Descriptor instead.
func (*IpRule) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{3}
}

func (x *IpRule) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *IpRule) GetType() IpRuleType {
	if x != nil {
		return x.Type
	}
	return IpRuleType_IP_RULE_TYPE_UNSPECIFIED
}

func (x *IpRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ListIpRulesRequest — запрос списка правил.
type ListIpRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Максимум элементов в ответе. Если 0 — сервер вернёт значение по умолчанию.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Токен для следующей страницы. Пусто для первой страницы.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Опциональный фильтр по типу правила.
	// Если IP_RULE_TYPE_UNSPECIFIED — вернуть все.
	FilterType    IpRuleType `protobuf:"varint,3,opt,name=filter_type,json=filterType,proto3,enum=antibruteforce.v1.IpRuleType" json:"filter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIpRulesRequest) Reset() {
	*x = ListIpRulesRequest{}
	mi := &file_v1_antibruteforce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIpRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIpRulesRequest) ProtoMessage() {}

func (x *ListIpRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIpRulesRequest.ProtoReflect.Descriptor instead.
func (*ListIpRulesRequest) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{4}
}

func (x *ListIpRulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIpRulesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListIpRulesRequest) GetFilterType() IpRuleType {
	if x != nil {
		return x.FilterType
	}
	return IpRuleType_IP_RULE_TYPE_UNSPECIFIED
}

// ListIpRulesResponse — ответ со списком правил.
type ListIpRulesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список правил на текущей странице.
	IpRules []*IpRule `protobuf:"bytes,1,rep,name=ip_rules,json=ipRules,proto3" json:"ip_rules,omitempty"`
	// Токен следующей страницы. Пусто, если страниц больше нет.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIpRulesResponse) Reset() {
	*x = ListIpRulesResponse{}
	mi := &file_v1_antibruteforce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIpRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIpRulesResponse) ProtoMessage() {}

func (x *ListIpRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIpRulesResponse.ProtoReflect.Descriptor instead.
func (*ListIpRulesResponse) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{5}
}

func (x *ListIpRulesResponse) GetIpRules() []*IpRule {
	if x != nil {
		return x.IpRules
	}
	return nil
}

func (x *ListIpRulesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateIpRuleRequest — запрос создания правила.
type CreateIpRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Type          IpRuleType             `protobuf:"varint,2,opt,name=type,proto3,enum=antibruteforce.v1.IpRuleType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIpRuleRequest) Reset() {
	*x = CreateIpRuleRequest{}
	mi := &file_v1_antibruteforce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIpRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIpRuleRequest) ProtoMessage() {}

func (x *CreateIpRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIpRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateIpRuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{6}
}

func (x *CreateIpRuleRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *CreateIpRuleRequest) GetType() IpRuleType {
	if x != nil {
		return x.Type
	}
	return IpRuleType_IP_RULE_TYPE_UNSPECIFIED
}

func (x *CreateIpRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// DeleteIpRuleRequest — запрос удаления правила.
type DeleteIpRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Type          IpRuleType             `protobuf:"varint,2,opt,name=type,proto3,enum=antibruteforce.v1.IpRuleType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIpRuleRequest) Reset() {
	*x = DeleteIpRuleRequest{}
	mi := &file_v1_antibruteforce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIpRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIpRuleRequest) ProtoMessage() {}

func (x *DeleteIpRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_antibruteforce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIpRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteIpRuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_antibruteforce_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIpRuleRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *DeleteIpRuleRequest) GetType() IpRuleType {
	if x != nil {
		return x.Type
	}
	return IpRuleType_IP_RULE_TYPE_UNSPECIFIED
}

var File_v1_antibruteforce_proto protoreflect.FileDescriptor

const file_v1_antibruteforce_proto_rawDesc = "" +
	"\n" +
	"\x17v1/antibruteforce.proto\x12\x11antibruteforce.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"W\n" +
	"\x13CheckAttemptRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"&\n" +
	"\x14CheckAttemptResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\":\n" +
	"\x12ResetBucketRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"q\n" +
	"\x06IpRule\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.antibruteforce.v1.IpRuleTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x90\x01\n" +
	"\x12ListIpRulesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12>\n" +
	"\vfilter_type\x18\x03 \x01(\x0e2\x1d.antibruteforce.v1.IpRuleTypeR\n" +
	"filterType\"s\n" +
	"\x13ListIpRulesResponse\x124\n" +
	"\bip_rules\x18\x01 \x03(\v2\x19.antibruteforce.v1.IpRuleR\aipRules\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"~\n" +
	"\x13CreateIpRuleRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.antibruteforce.v1.IpRuleTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\\\n" +
	"\x13DeleteIpRuleRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.antibruteforce.v1.IpRuleTypeR\x04type*b\n" +
	"\n" +
	"IpRuleType\x12\x1c\n" +
	"\x18IP_RULE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16IP_RULE_TYPE_WHITELIST\x10\x01\x12\x1a\n" +
	"\x16IP_RULE_TYPE_BLACKLIST\x10\x022\xd4\x04\n" +
	"\x15AntiBruteforceService\x12~\n" +
	"\fCheckAttempt\x12&.antibruteforce.v1.CheckAttemptRequest\x1a'.antibruteforce.v1.CheckAttemptResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/attempts:check\x12j\n" +
	"\vResetBucket\x12%.antibruteforce.v1.ResetBucketRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/buckets:reset\x12q\n" +
	"\vListIpRules\x12%.antibruteforce.v1.ListIpRulesRequest\x1a&.antibruteforce.v1.ListIpRulesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/ipRules\x12i\n" +
	"\fCreateIpRule\x12&.antibruteforce.v1.CreateIpRuleRequest\x1a\x19.antibruteforce.v1.IpRule\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/ipRules\x12q\n" +
	"\fDeleteIpRule\x12&.antibruteforce.v1.DeleteIpRuleRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/ipRules/{type}/{cidr}B9Z7github.com/boba180799/anti-bruteforce/api/proto/v1;pbv1b\x06proto3"

var (
	file_v1_antibruteforce_proto_rawDescOnce sync.Once
	file_v1_antibruteforce_proto_rawDescData []byte
)

func file_v1_antibruteforce_proto_rawDescGZIP() []byte {
	file_v1_antibruteforce_proto_rawDescOnce.Do(func() {
		file_v1_antibruteforce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_antibruteforce_proto_rawDesc), len(file_v1_antibruteforce_proto_rawDesc)))
	})
	return file_v1_antibruteforce_proto_rawDescData
}

var file_v1_antibruteforce_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_antibruteforce_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_antibruteforce_proto_goTypes = []any{
	(IpRuleType)(0),              // 0: antibruteforce.v1.IpRuleType
	(*CheckAttemptRequest)(nil),  // 1: antibruteforce.v1.CheckAttemptRequest
	(*CheckAttemptResponse)(nil), // 2: antibruteforce.v1.CheckAttemptResponse
	(*ResetBucketRequest)(nil),   // 3: antibruteforce.v1.ResetBucketRequest
	(*IpRule)(nil),               // 4: antibruteforce.v1.IpRule
	(*ListIpRulesRequest)(nil),   // 5: antibruteforce.v1.ListIpRulesRequest
	(*ListIpRulesResponse)(nil),  // 6: antibruteforce.v1.ListIpRulesResponse
	(*CreateIpRuleRequest)(nil),  // 7: antibruteforce.v1.CreateIpRuleRequest
	(*DeleteIpRuleRequest)(nil),  // 8: antibruteforce.v1.DeleteIpRuleRequest
	(*emptypb.Empty)(nil),        // 9: google.protobuf.Empty
}
var file_v1_antibruteforce_proto_depIdxs = []int32{
	0,  // 0: antibruteforce.v1.IpRule.type:type_name -> antibruteforce.v1.IpRuleType
	0,  // 1: antibruteforce.v1.ListIpRulesRequest.filter_type:type_name -> antibruteforce.v1.IpRuleType
	4,  // 2: antibruteforce.v1.ListIpRulesResponse.ip_rules:type_name -> antibruteforce.v1.IpRule
	0,  // 3: antibruteforce.v1.CreateIpRuleRequest.type:type_name -> antibruteforce.v1.IpRuleType
	0,  // 4: antibruteforce.v1.DeleteIpRuleRequest.type:type_name -> antibruteforce.v1.IpRuleType
	1,  // 5: antibruteforce.v1.AntiBruteforceService.CheckAttempt:input_type -> antibruteforce.v1.CheckAttemptRequest
	3,  // 6: antibruteforce.v1.AntiBruteforceService.ResetBucket:input_type -> antibruteforce.v1.ResetBucketRequest
	5,  // 7: antibruteforce.v1.AntiBruteforceService.ListIpRules:input_type -> antibruteforce.v1.ListIpRulesRequest
	7,  // 8: antibruteforce.v1.AntiBruteforceService.CreateIpRule:input_type -> antibruteforce.v1.CreateIpRuleRequest
	8,  // 9: antibruteforce.v1.AntiBruteforceService.DeleteIpRule:input_type -> antibruteforce.v1.DeleteIpRuleRequest
	2,  // 10: antibruteforce.v1.AntiBruteforceService.CheckAttempt:output_type -> antibruteforce.v1.CheckAttemptResponse
	9,  // 11: antibruteforce.v1.AntiBruteforceService.ResetBucket:output_type -> google.protobuf.Empty
	6,  // 12: antibruteforce.v1.AntiBruteforceService.ListIpRules:output_type -> antibruteforce.v1.ListIpRulesResponse
	4,  // 13: antibruteforce.v1.AntiBruteforceService.CreateIpRule:output_type -> antibruteforce.v1.IpRule
	9,  // 14: antibruteforce.v1.AntiBruteforceService.DeleteIpRule:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_antibruteforce_proto_init() }
func file_v1_antibruteforce_proto_init() {
	if File_v1_antibruteforce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_antibruteforce_proto_rawDesc), len(file_v1_antibruteforce_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_antibruteforce_proto_goTypes,
		DependencyIndexes: file_v1_antibruteforce_proto_depIdxs,
		EnumInfos:         file_v1_antibruteforce_proto_enumTypes,
		MessageInfos:      file_v1_antibruteforce_proto_msgTypes,
	}.Build()
	File_v1_antibruteforce_proto = out.File
	file_v1_antibruteforce_proto_goTypes = nil
	file_v1_antibruteforce_proto_depIdxs = nil
}
