// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: v1/antibruteforce.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AntiBruteforceService_CheckAttempt_FullMethodName = "/antibruteforce.v1.AntiBruteforceService/CheckAttempt"
	AntiBruteforceService_ResetBucket_FullMethodName  = "/antibruteforce.v1.AntiBruteforceService/ResetBucket"
	AntiBruteforceService_ListIpRules_FullMethodName  = "/antibruteforce.v1.AntiBruteforceService/ListIpRules"
	AntiBruteforceService_CreateIpRule_FullMethodName = "/antibruteforce.v1.AntiBruteforceService/CreateIpRule"
	AntiBruteforceService_DeleteIpRule_FullMethodName = "/antibruteforce.v1.AntiBruteforceService/DeleteIpRule"
)

// AntiBruteforceServiceClient is the client API for AntiBruteforceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AntiBruteforceService — сервис защиты от подбора паролей.
// Используется бэкендом авторизации для проверки попыток входа.
type AntiBruteforceServiceClient interface {
	// CheckAttempt проверяет попытку авторизации и сообщает,
	// разрешена ли она согласно whitelist, blacklist и лимитам.
	CheckAttempt(ctx context.Context, in *CheckAttemptRequest, opts ...grpc.CallOption) (*CheckAttemptResponse, error)
	// ResetBucket сбрасывает вёдра лимитов для указанного логина и/или IP.
	// Используется администраторами после легитимного входа пользователя.
	ResetBucket(ctx context.Context, in *ResetBucketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListIpRules возвращает список правил (whitelist и/или blacklist)
	// с поддержкой пагинации и фильтрации.
	ListIpRules(ctx context.Context, in *ListIpRulesRequest, opts ...grpc.CallOption) (*ListIpRulesResponse, error)
	// CreateIpRule добавляет новое правило.
	CreateIpRule(ctx context.Context, in *CreateIpRuleRequest, opts ...grpc.CallOption) (*IpRule, error)
	// DeleteIpRule удаляет правило по его CIDR и типу.
	DeleteIpRule(ctx context.Context, in *DeleteIpRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type antiBruteforceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiBruteforceServiceClient(cc grpc.ClientConnInterface) AntiBruteforceServiceClient {
	return &antiBruteforceServiceClient{cc}
}

func (c *antiBruteforceServiceClient) CheckAttempt(ctx context.Context, in *CheckAttemptRequest, opts ...grpc.CallOption) (*CheckAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAttemptResponse)
	err := c.cc.Invoke(ctx, AntiBruteforceService_CheckAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) ResetBucket(ctx context.Context, in *ResetBucketRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteforceService_ResetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) ListIpRules(ctx context.Context, in *ListIpRulesRequest, opts ...grpc.CallOption) (*ListIpRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIpRulesResponse)
	err := c.cc.Invoke(ctx, AntiBruteforceService_ListIpRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) CreateIpRule(ctx context.Context, in *CreateIpRuleRequest, opts ...grpc.CallOption) (*IpRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IpRule)
	err := c.cc.Invoke(ctx, AntiBruteforceService_CreateIpRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceServiceClient) DeleteIpRule(ctx context.Context, in *DeleteIpRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteforceService_DeleteIpRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteforceServiceServer is the server API for AntiBruteforceService service.
// All implementations must embed UnimplementedAntiBruteforceServiceServer
// for forward compatibility.
//
// AntiBruteforceService — сервис защиты от подбора паролей.
// Используется бэкендом авторизации для проверки попыток входа.
type AntiBruteforceServiceServer interface {
	// CheckAttempt проверяет попытку авторизации и сообщает,
	// разрешена ли она согласно whitelist, blacklist и лимитам.
	CheckAttempt(context.Context, *CheckAttemptRequest) (*CheckAttemptResponse, error)
	// ResetBucket сбрасывает вёдра лимитов для указанного логина и/или IP.
	// Используется администраторами после легитимного входа пользователя.
	ResetBucket(context.Context, *ResetBucketRequest) (*emptypb.Empty, error)
	// ListIpRules возвращает список правил (whitelist и/или blacklist)
	// с поддержкой пагинации и фильтрации.
	ListIpRules(context.Context, *ListIpRulesRequest) (*ListIpRulesResponse, error)
	// CreateIpRule добавляет новое правило.
	CreateIpRule(context.Context, *CreateIpRuleRequest) (*IpRule, error)
	// DeleteIpRule удаляет правило по его CIDR и типу.
	DeleteIpRule(context.Context, *DeleteIpRuleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAntiBruteforceServiceServer()
}

// UnimplementedAntiBruteforceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAntiBruteforceServiceServer struct{}

func (UnimplementedAntiBruteforceServiceServer) CheckAttempt(context.Context, *CheckAttemptRequest) (*CheckAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAttempt not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) ResetBucket(context.Context, *ResetBucketRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetBucket not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) ListIpRules(context.Context, *ListIpRulesRequest) (*ListIpRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIpRules not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) CreateIpRule(context.Context, *CreateIpRuleRequest) (*IpRule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIpRule not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) DeleteIpRule(context.Context, *DeleteIpRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIpRule not implemented")
}
func (UnimplementedAntiBruteforceServiceServer) mustEmbedUnimplementedAntiBruteforceServiceServer() {}
func (UnimplementedAntiBruteforceServiceServer) testEmbeddedByValue()                               {}

// UnsafeAntiBruteforceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiBruteforceServiceServer will
// result in compilation errors.
type UnsafeAntiBruteforceServiceServer interface {
	mustEmbedUnimplementedAntiBruteforceServiceServer()
}

func RegisterAntiBruteforceServiceServer(s grpc.ServiceRegistrar, srv AntiBruteforceServiceServer) {
	// If the following call panics, it indicates UnimplementedAntiBruteforceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AntiBruteforceService_ServiceDesc, srv)
}

func _AntiBruteforceService_CheckAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).CheckAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_CheckAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).CheckAttempt(ctx, req.(*CheckAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_ResetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).ResetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_ResetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).ResetBucket(ctx, req.(*ResetBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_ListIpRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIpRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).ListIpRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_ListIpRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).ListIpRules(ctx, req.(*ListIpRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_CreateIpRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIpRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).CreateIpRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_CreateIpRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).CreateIpRule(ctx, req.(*CreateIpRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforceService_DeleteIpRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIpRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServiceServer).DeleteIpRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforceService_DeleteIpRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServiceServer).DeleteIpRule(ctx, req.(*DeleteIpRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AntiBruteforceService_ServiceDesc is the grpc.ServiceDesc for AntiBruteforceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiBruteforceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "antibruteforce.v1.AntiBruteforceService",
	HandlerType: (*AntiBruteforceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAttempt",
			Handler:    _AntiBruteforceService_CheckAttempt_Handler,
		},
		{
			MethodName: "ResetBucket",
			Handler:    _AntiBruteforceService_ResetBucket_Handler,
		},
		{
			MethodName: "ListIpRules",
			Handler:    _AntiBruteforceService_ListIpRules_Handler,
		},
		{
			MethodName: "CreateIpRule",
			Handler:    _AntiBruteforceService_CreateIpRule_Handler,
		},
		{
			MethodName: "DeleteIpRule",
			Handler:    _AntiBruteforceService_DeleteIpRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/antibruteforce.proto",
}
