services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: anti-bruteforce:local
    container_name: abf-app
    ports:
      - "8080:8080" # REST
      - "9090:9090" # gRPC
    environment:
      GRPC_ADDR: ":9090"
      HTTP_ADDR: ":8080"
      LOGIN_LIMIT: "10"
      PASSWORD_LIMIT: "100"
      IP_LIMIT: "1000"
      BUCKET_TTL: "10m"
    restart: unless-stopped
